{% set name = "napari-vedo-bridge" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-vedo-bridge-{{ version }}.tar.gz
  sha256: 7b84a6c01b91a135c1040e2fbe34d66b03b2eeda9cae23c6d6690593325e9997

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - numpy
    - python >={{ python_min }}
    - qtpy
    - vedo >=2023.4.6
    - vtk

test:
  imports:
    - napari_vedo_bridge
    - napari_vedo_bridge._cutter_widget
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/jo-mueller/napari-vedo-bridge
  summary: Transfer mesh data between napari and vedo for interactive processing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jo-mueller
